---
- hosts: localhost
  become: true
  pre_tasks:
    - name: Setting up openssh requirements
      apt:
        name: [
        build-essential, 
        libssl-dev,
        libffi-dev,
        python3-dev,
        python3-pip,
        ]
        update_cache: yes
      retries: 3

    - name: python pip install cryptography
      pip:
        name: cryptography
        executable: pip3

    - name: python pip install pyopenssl
      pip:
        name: pyopenssl
        executable: pip3

    - name: python pip install ndg-httpsclient
      pip:
        name: ndg-httpsclient
        executable: pip3

    - name: python pip install pyasn1
      pip:
        name: pyasn1
        executable: pip3

  tasks:
      - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa) and encrypted private key
        community.crypto.openssh_keypair:
          path: ./example_id_ssh_rsa
          passphrase: super_secret_password